[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.setup]
nixPkgs = [
        "php82",
            "php82Extensions.intl",
                "php82Extensions.gd",
                    "php82Extensions.zip",
                        "php82Packages.composer",
                            "nodejs_22"
]

[phases.install]
cmds = [
        "composer install --ignore-platform-reqs --no-dev --optimize-autoloader",
            "npm install"
]

[phases.build]
cmds = ["npm run build"]