providers = ["php", "node"]

[variables]
NIXPACKS_NODE_VERSION = "22"
NIXPACKS_PHP_VERSION = "82"
NIXPACKS_PHP_EXTENSIONS = "intl gd zip"

[phases.install]
cmds = [
        "composer install --ignore-platform-reqs --no-dev --optimize-autoloader",
            "npm install"
]

[phases.build]
cmds = ["npm run build"]